### ISSUE TITLE
Monospaced task lists

### ISSUE THREAD

**Issue by hsiktas** [colineckert/obsidian-things#10]
The default theme automatically turns `- [ ]` into monospaced(?) symbols that don't shift the text around if I check/uncheck an entry off. Here is an example:

![image](https://user-images.githubusercontent.com/4571159/140742319-f4b4e0b8-4a47-4f8b-a646-bcb724cd6551.png)

It doesn't look that nice with this theme:
![image](https://user-images.githubusercontent.com/4571159/140742379-9b5f4def-13f4-40f2-b0e0-766938137879.png)

Is it possible to add this to this theme? Otherwise, it looks awesome, even on non-Apple platforms. 👍

**Comment by colineckert** [comment]
Nice catch! I've updated task boxes to be monospace in edit mode and will include the change in the next release (expected to publish within the next couple of days). Thanks!
