### ISSUE TITLE
[SUGGESTION] Improve highlights appearence

### ISSUE THREAD

**Issue by bdalia** [colineckert/obsidian-things#102]
Thank you for this so beautiful and simple theme!

I noticed that highlights are not so readable because there is not enough padding around the highlighted text. Moreover, the dark theme show highlights in an "ugly" dark green color (i think it should be yellow).

Anyway it may be very useful to have additional options to customize highlights.

Kind regards.
Bart.

**Comment by colineckert** [comment]
Hi @bdalia I've added some padding around highlighted text. Are seeing a green highlight experience on your end? Mind sending a screenshot? 

Here is how it is displaying now for me, pictured amongst other colors for reference:
<img width="687" alt="Screen Shot 2022-12-11 at 6 01 44 AM" src="https://user-images.githubusercontent.com/60206665/206908176-cb953041-e649-4a10-a344-0f6d9626fe72.png">

**Comment by bdalia** [comment]
Hi @colineckert and thank you for the reply. Now is more readable with a little padding.

On the yellow matter i mean the color seems not so yellowish, i photoshopped your image with an example of what i mean (html code is #99802 and i make text full white to increase readability).

<img width="687" alt="206908176-cb953041-e649-4a10-a344-0f6d9626fe72" src="https://user-images.githubusercontent.com/54666718/207368337-42b9aa9b-72f4-423f-856e-ae1a25d360ee.png">

Kind regards.

**Comment by colineckert** [comment]
Hey, @bdalia I just published a new version (2.1.3) that adds the ability to set custom highlight colors (light and dark mode) via the Style Settings plugin. Hopefully, that resolves this issue for you by allowing you to easily set whatever colors you'd like. Let me know if this works and if so, just close this issue. Thanks!
