### ISSUE TITLE
[Feature Request] Display Markdown tasks as 'cancelled'

### ISSUE THREAD

**Issue by tomdaly** [colineckert/obsidian-things#103]
Hi, thanks for writing this theme! Its my new favourite theme for Obsidian by far. I have one feature request to display a markdown task as 'cancelled'.

Things 3 has the ability to cancel a todo, marking it with a cross instead of a tick. Markdown does not (afaik) have a concept of a 'cancelled' task, but I tend to use `[-]` as it aligns with other apps (and Things [supports](https://culturedcode.com/things/support/articles/4651820/) `[~]`, it would be great if it could do both!) 

## Current Behaviour

A 'cancelled' todo (marked with `-`) is displayed with the tick icon and **uncompleted** task foreground font colour (white in dark mode)

![Screenshot 2022-11-02 at 13 50 13](https://user-images.githubusercontent.com/2606341/199506781-578c2dfe-d6ca-4530-8ad3-8a6bfddb9d0d.jpg)

represented in markdown:
```
- [ ] open todo
- [x] completed todo
- [-] cancelled todo
```

## Desired Behaviour

A cancelled todo is displayed with a cross (X) icon and the **completed** task foreground font colour (grey)

![Screenshot 2022-11-02 at 13 51 42](https://user-images.githubusercontent.com/2606341/199506969-52c2248c-b879-4df4-ae40-a5b7defc1fa0.jpg)

Let me know if you want any more info, or if you can point me to the classes where this is parsed & displayed I'm happy to help contribute.

**Comment by colineckert** [comment]
hey, @tomdaly I just released v2.1 of Things, which supports canceled checkboxes and much more (see [here](https://minimal.guide/Block+types/Checklists#Checkbox+icons) for an idea of what is supported now in Things too). Update your theme and if all looks good, please close this issue. Thanks!

**Comment by colineckert** [comment]
Hey @tomdaly hopefully this looks good! Closing the issue but pls feel free to reopen it if you have any problems or feedback. Cheers!

**Comment by tomdaly** [comment]
hey @colineckert, sorry I missed your comment last week. I've updated to v2.1, it looks great! the new checklist features are awesome too, a very clean solution to the problem. thanks for resolving this 🚀
