### ISSUE TITLE
The color of the tags in dark mode are incorrect

### ISSUE THREAD

**Issue by HybridRbt** [colineckert/obsidian-things#105]
This is very strange, but the tag display in dark mode on mobile seems to be incorrect. Please see the screenshots.

Dark mode on desktop: 
<img width="542" alt="截屏2022-11-03 下午10 31 54" src="https://user-images.githubusercontent.com/6162974/199879729-5e8089ba-dcf8-4dd5-bf80-3012607a5ad7.png">
Dark mode on mobile:
![IMG_1674](https://user-images.githubusercontent.com/6162974/199879845-5d28ee19-4616-4d11-89bc-579788aad78a.PNG)

Light mode on desktop: 
<img width="349" alt="截屏2022-11-03 下午10 36 25" src="https://user-images.githubusercontent.com/6162974/199879929-9df7d751-c04e-4ee0-b52d-aa918467447c.png">
Light mode on mobile:
![IMG_716927A8029E-1](https://user-images.githubusercontent.com/6162974/199880232-bcb96847-0c8a-498d-aede-b1e0a11cc43c.jpeg)

As you can see, the dark mode on mobile is the only one that's different with the others. I have tried everything I can think of: turn off/remove all community plugins one by one, or turn off community plugins altogether, even deleted the app from my phone and reinstalled again, but it's still the same. 

I have updated both the iOS app and the theme itself to the latest. I have also checked the style settings plugin (before I turned it off), and the corresponding settings are all the same with the desktop.

**Comment by colineckert** [comment]
Hey @HybridRbt, this should now be fixed! Update your theme and if it's looking good to you, please close this issue. Thanks for the feedback and for using Things! :)

**Comment by HybridRbt** [comment]
Yes, it's working now! Thanks for the fix.
