### ISSUE TITLE
Checkbox Styling

### ISSUE THREAD

**Issue by zhanghanghitomi** [colineckert/obsidian-things#106]
Could you pls support other status in the checkbox styling, say, those in https://minimal.guide/Block+types/Checklists. Thx.

**Comment by colineckert** [comment]
hey @zhanghanghitomi I just released v2.1 of Things, which supports checkbox styling. Update your theme and if all looks good, please close this issue. Thanks!

**Comment by zhanghanghitomi** [comment]
Thanks for your feedback. It works perfectly! thank you.
