### ISSUE TITLE
Option to Disable Heading Underline

### ISSUE THREAD

**Issue by dvdmtw98** [colineckert/obsidian-things#107]
It would be great to have the ability to disable the Heading Underline that happens only for H2.

In my case I already use `---` to denote separation and the underline that is added by H2 kind of makes my file look messy.

**Comment by colineckert** [comment]
Hey @dvdmtw98 I just published v2.0.6 which adds support for this via the Style Settings plugin, under Headings > H2. Check it out and if it looks good, please close this issue. Thanks so much! :)
