### ISSUE TITLE
The code renders badly in reading mode 

### ISSUE THREAD

**Issue by JaceJu-frog** [colineckert/obsidian-things#108]
## The code renders badly in reading mode 

When in preview mode,my html code renders well ,like figure 1.
![image](https://user-images.githubusercontent.com/63134846/206892259-21d4065a-e5b9-4076-bdc3-f173551a8b5c.png)

But when I switches to reading mode, the text in angle brackets suddenly turns on the same color as the tag,such as <li>,<ol>.
![image](https://user-images.githubusercontent.com/63134846/206892256-61e7f615-1db0-42df-ba2d-08e436bdb5da.png)

This tiny mistake influences my using experience,hope a quick solution.

**Comment by colineckert** [comment]
Hey @JaceJu-frog this bug should be fixed now. Update your theme and if all looks good, please close this issue. Thanks!
