### ISSUE TITLE
Add margin/ padding around Tags

### ISSUE THREAD

**Issue by dvdmtw98** [colineckert/obsidian-things#110]
It would be great if there was some margin that was present around tags especially towards the bottom as when there are multiple lines of tags the tags all seem to be clubbed/ combined together. 

I have tables in my Vault that has tags as such and they look a little strange due to the lack of margin. 
Hope this is something that can be added

![image](https://user-images.githubusercontent.com/31100937/209064665-40505ef2-d3d4-4b92-b411-f37c9b9a3124.png)

**Comment by colineckert** [comment]
hey @dvdmtw98 qq, does this issue also appear in the default theme?

**Comment by dvdmtw98** [comment]
Interesting...seems to occur for me on the default theme as well. @colineckert could this be an issue related to a plugin ? In your picture it does not look like its overlapping.

![image](https://user-images.githubusercontent.com/31100937/210178773-87454a1c-460b-4da0-a01e-9f2689ee7dc2.png)

**Comment by colineckert** [comment]
I don't believe so. I have Advanced Tables installed but disabling did not change. What OS are you running? Windows or Linux?

**Comment by dvdmtw98** [comment]
I am on Windows. The overlapping seems to occur to some extend on mobile (Android) as well. I checked tags in tables in the Sandbox Vault (Windows) but it is overlapping there as well. Could it be an Obsidian Issue ? Should I open a Bug Report on the Forum ?

**Comment by colineckert** [comment]
Yep I think that would be the best next step. I'll close this issue for now since it seems to be an Obsidian bug, not Things. Thanks!
