### ISSUE TITLE
Enhanced Code Block 1st Line Text Alignment Bug (when Language not specified)

### ISSUE THREAD

**Issue by dvdmtw98** [colineckert/obsidian-things#115]
There seems to be an alignment issue in the new enhanced code block when the language for the block is not specified. 
This only happens in Reading View

![Enhanced Code Block](https://user-images.githubusercontent.com/31100937/210593153-01b7fdb9-f613-40db-914d-e79b4b3c6cff.png)

**Comment by colineckert** [comment]
Hey @dvdmtw98, thank you for creating this issue! @luanhaixin kindly added code to resolve this bug in #117, which I've added up and pushed up. Pls update your theme and if it looks good on your end, pls close this issue. Thanks again!
