### ISSUE TITLE
Code block broken in Source Mode when << is used

### ISSUE THREAD

**Issue by jwierzbo** [colineckert/obsidian-things#116]
When I use in my code block following signs `<<` then in source mode i see everything as one big Code block
<img width="1012" alt="SreenShot 2023-01-05 at 00 01 23@2x" src="https://user-images.githubusercontent.com/2726393/210666160-292f019e-7237-4dca-ab8e-542d5b927e05.png">

Everything works fine in Reading Mode:
<img width="1010" alt="SreenShot 2023-01-05 at 00 01 34@2x" src="https://user-images.githubusercontent.com/2726393/210666190-4de5fe11-aa23-4bbc-9065-909b5e527b94.png">

Once one `<` sign is removed then everything works as expected in source mode:
<img width="1013" alt="SreenShot 2023-01-05 at 00 02 26@2x" src="https://user-images.githubusercontent.com/2726393/210666260-f50b2e8e-da6a-4102-b063-17e640dd218a.png">

**Comment by jwierzbo** [comment]
Looks like this is an internal Obsidian bug:
https://forum.obsidian.md/t/intended-code-block-with-text-will-break-further-code-blocks/42294

**Comment by colineckert** [comment]
Oh, interesting. I haven't come across this yet, but thanks for flagging it. Glad it's not specific to Things 😅 

Since it's an Obsidian bug, I'm going to close this issue. Thanks for using Things and providing feedback!
