### ISSUE TITLE
Cursor doesn't interact with vim mode properly

### ISSUE THREAD

**Issue by vsinha** [colineckert/obsidian-things#12]
If i have the obsidian built-in vim mode enabled, and I'm in normal mode (esc), and i hit `i` to go into insert mode, the cursor shows up to the *right* of the current character. However, text is inserted (correctly) to the left of the character.

I poked around the CSS a bit but I'm really not a CSS expert and couldn't find where the input caret might be affected.

Thanks!

**Comment by colineckert** [comment]
Hmm, I'm no vim expert, but I can certainly try to look into this. Thanks for raising the issue!

**Comment by colineckert** [comment]
Hey, @vsinha are you experiencing this issue anymore? It should have resolved itself with the release of Obsidian v1 and Things v2. I have been using vim mode for some time and am not experiencing issues, so closing this issue. Feel free to reopen if you find any bugs. Cheers!
