### ISSUE TITLE
Feature Request: Disable Kanban Styling

### ISSUE THREAD

**Issue by mudkipdev** [colineckert/obsidian-things#122]
Adding an option for disabling the styling for the Kanban plugin would be great. I am referring to the following lines of code:

https://github.com/colineckert/obsidian-things/blob/main/theme.css#L1020-L1076

**Comment by colineckert** [comment]
Thanks @mudkipdev for creating the issue! I've added an option to the Style Settings plugin to disable the Kanban plugin styling. Lmk if you find any bugs. If not, please close this issue. thanks!

**Comment by mudkipdev** [comment]
I'll let you know how the testing goes. Thanks.

**Comment by mudkipdev** [comment]
Working fine, thanks!
