### ISSUE TITLE
Better caption than "language-cpp"

### ISSUE THREAD

**Issue by trick-treat** [colineckert/obsidian-things#126]
Your code block's pretty good but "language-cpp" isn't a nice caption. As for me "C++" is brief and better.

![image](https://user-images.githubusercontent.com/13872416/227855677-ae768d26-7f3b-4100-9eda-8faa7dcbc98d.png)

**Comment by colineckert** [comment]
@nigelinux this relevant to reading view only and unfortunately, i don't have a good solution, as i'm using the `pre` tag's class as the content, and i don't have control over it.
<img width="197" alt="Screenshot 2023-06-26 at 9 57 08 PM" src="https://github.com/colineckert/obsidian-things/assets/60206665/37816cf8-d5f2-44bd-98d3-87b73e7c1b97">

i'm thinking of reworking/reverting code block styling, so hoping to fix this soon

**Comment by colineckert** [comment]
hey! so i've actually reverted to the simple/non-numbered code blocks. this experiment failed imo and the code blocks were too buggy and too hard to maintain. reverting to the simpler and cleaner code blocks better aligns with the Things style. Thanks!
