### ISSUE TITLE
Dark Mode - hard to see active row in menus

### ISSUE THREAD

**Issue by CrossTheRubicon** [colineckert/obsidian-things#13]
In Dark Mode, when you are in Command Palette and Quick Switcher menus, it is very hard to see which row is active when you are navigating options.

**Comment by colineckert** [comment]
Good catch! I updated the theme so selected items are more visible (I actually love how it turned out more than the original, hint: it uses the Things blue). I'll push the update and include it in the next release - expected to publish today or tomorrow. Thanks!

**Comment by CrossTheRubicon** [comment]
Thanks, it's a great theme and I'm really enjoying using it!
