### ISSUE TITLE
Line numbers in code block reset all to 1 in longer code blocks

### ISSUE THREAD

**Issue by SkMag9** [colineckert/obsidian-things#131]
I have a longer script in one of my Obsidian notes and whenever I scroll down past line 32 (line 32 is no longer visible) the line numbers all reset to 1.
The numbers return to normal when scrolling back up to around line 5 or 6 . 

![image](https://user-images.githubusercontent.com/79118346/236846811-73bc2da9-ed0f-4a54-bf4b-fda42d9b6a52.png)

**Comment by colineckert** [comment]
hey @SkMag9 thanks for the issue. i've actually reverted to the simple/non-numbered code-blocks. this experiment failed imo and the code blocks were too buggy and too hard to maintain. reverting to the simpler and cleaner code blocks better aligns witht the Things style. Thanks!
