### ISSUE TITLE
How can I change font "JetBrains Mono" using snippets?

### ISSUE THREAD

**Issue by qizhengyang2017** [colineckert/obsidian-things#135]
Hello,
I'm not used to ligatures, so I want to change "JetBrains Mono" to "JetBrains Mono NL". How can I do this using snippets?

**Comment by colineckert** [comment]
hey @qizhengyang2017 happy to help. you shouldn't need a snippet. obsidian supports custom font settings under Appearance > Monospace font. if you have it installed on your machine, you should be able to search and add it as i have here:
<img width="589" alt="Screenshot 2023-06-04 at 5 25 16 PM" src="https://github.com/colineckert/obsidian-things/assets/60206665/fd97b213-996b-4f45-82e7-ae947b21967d">

if you want to try with a snippet, you can try creating a new `font.css` file and move it to obsidian's snippet directory and add this line to the file to override my font variable: 
```css
  --font-monospace-theme: 'JetBrains Mono NL';
```

let me know if either of these works and if so, please close this issue. thanks!

**Comment by claremacrae** [comment]
It worked for me, many thanks for writing up the fix.
