### ISSUE TITLE
Title misalignment with 'Readable line length' option enabled

### ISSUE THREAD

**Issue by k2pctdn** [colineckert/obsidian-things#136]
When Obsidian's "Readable line length" option is enabled, the title of the note is not aligned with content (the screenshot below)
![1](https://github.com/colineckert/obsidian-things/assets/7236661/ad7d946b-baa8-45c3-849b-3aceee1f5545)

When this option is disable, the title aligns well with the content:
![image](https://github.com/colineckert/obsidian-things/assets/7236661/dd854793-b147-4659-bd63-76c6b72d93c0)

- Community plugins that I use (in case of any conflicts): File Explorer Note Count, Homepage, Icon Folder, Obsidian Git.
- Things theme version 2.1.9.
- Obsidian version 1.3.5.

**Comment by gkjpettet** [comment]
Just to add that I can confirm this bug.

**Comment by colineckert** [comment]
hi @k2pctdn & @gkjpettet, thanks for flagging this issue! i reverted a recent change that introduced this bug and should now be fixed. update your theme to this latest version: https://github.com/colineckert/obsidian-things/releases/tag/2.1.12

pls close this issue if the bug is resolved, thanks!

**Comment by k2pctdn** [comment]
Hi @colineckert ,

I just updated the theme to the latest version and confirmed that the bug has been fixed. Thank you for your great work!

**Comment by colineckert** [comment]
awesome! thanks for confirming and apologies for the delay in resolving. i sincerely appreciate you all using the theme and sharing feedback. cheers!
