### ISSUE TITLE
Conflict with CodeMirror Options on Tasks?

### ISSUE THREAD

**Issue by richardlm** [colineckert/obsidian-things#14]
This may be an edge case, but I thought it worth reporting anyway.

I use 'Tasks' and 'CodeMirror Options' to render tasks in Edit Mode.

Having just installed Things theme I see that the task checkboxes are not rendered as boxes, but as bullets.

In edit mode:
![Screenshot 2021-11-10 105419](https://user-images.githubusercontent.com/15072925/141101229-06293a36-44f2-4671-9bcd-aedaae30f93a.png)

and in Preview mode:
![Screenshot 2021-11-10 105447](https://user-images.githubusercontent.com/15072925/141101327-ea48b51c-9c3b-4d96-b076-6d30e404ab1a.png)

With my usual theme - Yin and Yang - the checkboxes appear in edit mode.

Thanks.

**Comment by colineckert** [comment]
Hey, thanks for raising this issue! I appreciate your patience in my response, it's been a busy week. 

How would I replicate this? is it as simple as installing the 'Tasks' and 'CodeMirror Options' plugins, and I _should_ see the checkboxes in edit mode?

**Comment by richardlm** [comment]
Hi Colin
Thanks for responding! I am not sure what has changed in the last 4 days but it now looks better - I get check boxes in edit mode, but also bullets: 
![image](https://user-images.githubusercontent.com/15072925/141690273-e67f278b-ec86-4946-aa41-4e6b2e71810a.png)

In preview mode I just get the check boxes.

This now looks the same as with my previous theme (Yin & Yang) and is workable. As we're in a transition period with "Live Preview" actively being introduced (& CodeMirror being phased out?) I'm happy to see how things (no pun intended) develop.

**Comment by colineckert** [comment]
Awesome news! glad it's working better for you now. Thanks again for submitting the issue!

**Comment by JanKazimir** [comment]
Just found this by googling, I have the same the same problem as OP. 
Interesting to point out that the dot actually works as a checkbox, albeit a _tiny_ one.
The problem seems to be related to the theme.

I have tried: (all in dark mode).
Obsidian gruvbox (has the problem)
Obsidian nord (has the problem)
Minimal (No problem)
and a few more, most with problems.
I see no relations, except that the themes I like don't seem to work...
