### ISSUE TITLE
Grayed out text for "merged PR" checkbox

### ISSUE THREAD

**Issue by steynh** [colineckert/obsidian-things#140]
Hi, thanks for your work on this amazing theme. :) 

I'd like to request a feature regarding the special checkboxes, feel free to ignore.

For the "merged PR" checkbox, I would like the text to be grayed out similar to the normal "done" checkbox. I'd be happy with either this behavior as default, or an option to configure in Style Settings.
```markdown
- [M] merged pull request (not grayed out)
- [x] done (grayed out)
```

Thanks for considering.

**Comment by lukasschwab** [comment]
I want this too! I'll see if I can get a PR open today.

**Comment by colineckert** [comment]
thanks for creating this issue @steynh and the PR @lukasschwab - i just merged it the changes!
