### ISSUE TITLE
Filename title doesn't align left with the rest of content in editing mode.

### ISSUE THREAD

**Issue by joshdoyle** [colineckert/obsidian-things#142]
The filename doesn't align with the rest of the content when in editing mode. It does align in reading mode. I am unsure if this is a setting I have changed or a problem with the Things Theme. I am using the Things theme (ver. 2.1.11) with Obsidian (ver. 1.3.5). The alignment is correct if I switch to another theme.

![Screenshot 2023-07-06 at 8 14 22 AM](https://github.com/colineckert/obsidian-things/assets/1417704/95f5cef1-2e2b-4313-85a1-2fdbfeb6b374)

**Comment by colineckert** [comment]
hi @joshdoyle, thanks for creating this issue! i reverted a recent change that introduced this bug and should now be fixed. update your theme to this latest version: https://github.com/colineckert/obsidian-things/releases/tag/2.1.12

pls close this issue if the bug is resolved, thanks!
