### ISSUE TITLE
<progress> Bar Styling

### ISSUE THREAD

**Issue by jamie9090** [colineckert/obsidian-things#148]
Would love to mirror Minimal's colour grading for <progress> bars :)

https://minimal.guide/progress-bars

<img width="565" alt="CleanShot 2023-09-03 at 18 15 50@2x" src="https://github.com/colineckert/obsidian-things/assets/69635548/38918c85-6c7d-4804-ab89-920883ffa183">

**Comment by Azhc** [comment]
I also hope

**Comment by moziar** [comment]
Waiting @colineckert to review the code.

**Comment by colineckert** [comment]
Sorry for the delay. Took some time away from actively managing this theme. PR has been merged. Thanks @moziar and also @jamie9090 for opening the issue!
