### ISSUE TITLE
Filename not aligned with file content

### ISSUE THREAD

**Issue by max** [colineckert/obsidian-things#15]
Thank you for creating this wonderful theme. I noticed a small visual bug: the filename and the content of the file are not vertically aligned. See the screenshot below.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/111631/141649477-72304391-6207-4b46-8028-a11c82e9028f.png">

**Comment by colineckert** [comment]
Thanks for flagging this! To confirm, this is only in editor or also in preview mode on your end? 

I don't see it on my end (see screenshots).

Edit mode:
<img width="397" alt="Screen Shot 2021-11-13 at 9 37 53 AM" src="https://user-images.githubusercontent.com/60206665/141653564-58d39bd2-8ce1-4f78-95c4-c11cb4123d58.png">

Preview mode:
<img width="365" alt="Screen Shot 2021-11-13 at 9 38 22 AM" src="https://user-images.githubusercontent.com/60206665/141653583-d362a771-e1f1-4579-bfc3-d17ea1d1f009.png">

 When was the last time you updated your theme?

**Comment by NickChristensen** [comment]
I'm seeing the same misalignment. New vault, 100% default settings (other than selecting the Things theme).
<img width="1329" alt="Screen Shot 2021-11-17 at 2 09 43 PM" src="https://user-images.githubusercontent.com/613826/142274859-83d9f08d-74e3-42aa-8717-ca37e3f32fbe.png">

**Comment by NickChristensen** [comment]
This looks to be fixed for me on Obsidian v0.13.12 and 1.6.0 of this theme, in both `Live Preview` and `Source` modes.

**Comment by colineckert** [comment]
Thanks for confirming @NickChristensen! @max has this been resolved for you also? If so, I'll close the issue.

**Comment by ElysiaAtroviridis** [comment]
@colineckert Also saying a big thank you for this theme that looks great w/o additional plug-ins. 

Unfortunately I have this very same issue with both Live-Preview on/off on both the app and theme's most recent versions.

Toggling between Editing and Reading moves the entire body on a horizontal plane, but neither aligns reliably with the 'Title' up top at various window sizes. No CSS Snippets, no community plugins.

**Comment by mgussekloo** [comment]
I have the same thing, just installed Obsidian and selected this theme (no other plugins / snippets)

**Comment by colineckert** [comment]
Closing this issue as it is no longer relevant since Obsidian v1. Cheers!

**Comment by alex3305** [comment]
For me this issue has popped up again:

![image](https://user-images.githubusercontent.com/5155694/234539742-917a77c4-72b6-48ae-a09e-cf2183352847.png)

Using Obsidian 1.1.16 and the latest Things theme.

**Comment by jumpingfrog0** [comment]
Filename Title not align left with content after upgrade version to 2.1.9
![image](https://user-images.githubusercontent.com/7556575/236990373-f730182c-f1e2-4086-8e43-8ab181d242d6.png)

**Comment by chrislicodes** [comment]
Hey, I encounter the same issue after updating the theme today. ._.

<img width="822" alt="image" src="https://github.com/colineckert/obsidian-things/assets/45950730/a338223f-15cf-4d78-875f-bc89b83bd4ee">
