### ISSUE TITLE
Tab title bar only visible on hover

### ISSUE THREAD

**Issue by totholz5d** [colineckert/obsidian-things#151]
Hi there,

I have the impression that the behavior of the 
tab title bar (with path/name) changed since the last update

Now it is only visible when I hover over it.

I would like the full path and filename in the top tab bar to be always shown.

Is there a way to set that it always stays visible?
I don't see an option to set this in the style setting (there is one in for the minimal theme)

Am I missing something?

**Comment by colineckert** [comment]
hey @totholz5d thanks for creating this issue. I just pushed up an update (v2.1.17) that adds a toggle accessible via the style settings plugin to always show the title bar. If this resolves the issue for you, please close the issue. Thanks for using Things and sharing your feedack!

**Comment by totholz5d** [comment]
Thanks!
It works great. I really missed it. Thank for your fast response and for the great theme!
