### ISSUE TITLE
Feature Request: Old Code Block Styling

### ISSUE THREAD

**Issue by TWCCarlson** [colineckert/obsidian-things#152]
In commit f38177d5a830fd67448f269893683a81121071f4 the numbering and styling for code blocks was removed.

I actually quite liked this feature, especially the different appearance for the lines containing the triple dashes. I find it plays especially well with Admonitions and language-tagged code blocks.

If you would like to keep the new appearance, I would humbly suggest you add it as an option that is default off.

You also still have numbered code blocks listed as a feature in your readme.

**Comment by colineckert** [comment]
hey @TWCCarlson pls update your theme to the latest v2.1.18. The toggle has been added (disabled by default)! Lmk if you have any questions and pls close this issue if all looks good. thanks!

**Comment by TWCCarlson** [comment]
Perfect! Thank you.
