### ISSUE TITLE
Always show title bar when editing name

### ISSUE THREAD

**Issue by dsent** [colineckert/obsidian-things#155]
If “Always show title bar” is not enabled in style setting, then the title bar is hidden even when editing the name of the current file if you don't hover the mouse over it, e.g., by pressing F2. Therefore, you can't see what you're editing (in fact, that you're editing at all).

I believe this is not an intended behavior.

**Comment by colineckert** [comment]
hey @dsent thanks for creating this issue. i actually backtracked this change, so the titlebar is now present by default. it caused some unintended issues on mobile too. thanks!
