### ISSUE TITLE
Unable to view starting characters as it takes full width of the screen

### ISSUE THREAD

**Issue by Sachin-12** [colineckert/obsidian-things#16]
I'm using Android 11. I'm unable to see the first character of every sentence due to the screen being a bit curved at the edges. Needs some margin or padding I guess. I have attached a screenshot from my mobile.
![IMG_20211114_053417](https://user-images.githubusercontent.com/24960422/141662571-2faa3e93-a7a2-4ce2-91ac-87c0086c71e4.jpg)

**Comment by Sachin-12** [comment]
Closing this as it was due to my tempered glass being broken at the edges.

**Comment by colineckert** [comment]
Thanks! Any helpful resources you recommend on service workers lol? I'm actually looking to learn more about them too?

**Comment by Sachin-12** [comment]
- Hey. Sorry for the late reply. I too couldn't find all in one resource for service workers. But if you need any help, you could ping me on discord "sachin#9989". 
- Things theme is highly usable on mobile but I feel it could have a slight margin on the left and right as some people have their edges covered a bit if they have a screen protector.
