### ISSUE TITLE
No padding on iOS / iPadOS?

### ISSUE THREAD

**Issue by dpmeltz** [colineckert/obsidian-things#17]
When I'm using the theme on my iPhone and iPad, there's no padding around the screen like is being shown in the preview imagine. Text begins touching the left-most edge of the screen, and continues all the way to the right-most. It needs a little buffer space.

iPhone 13, iPad Pro 11 (2018), both running current release OS, and Obsidian 1.0.5

**Comment by colineckert** [comment]
Hey @dpmeltz, thanks for submitting an issue. Out of curiosity, have you enabled the beta WYSIWYG editor? That feature introduced some weird things in the css styling, so want to check if that's the source here too.

**Comment by dpmeltz** [comment]
On desktop it's fine (not seeing issue with live preview), mobile is where I'm seeing the issue, so there's no beta wysiwyg to turn on.

I've turned all my community plugins off and still see like this.

**Comment by dpmeltz** [comment]
I feel really stupid. I have "readable line length" in editor settings turned off. If I turn it on I get padding. Probably need something there.

**Comment by colineckert** [comment]
Ahh ok cool. No worries, glad we could identify the issue. Thanks for using the theme! Let me know if you find any other issues :)
