### ISSUE TITLE
H2 and H3 coloring

### ISSUE THREAD

**Issue by StevenMichels** [colineckert/obsidian-things#19]
Thanks for a great theme! Is there any reason why H2 and H3 are the same color?

That's pretty nit picky, I know, but it's otherwise perfect!

**Comment by colineckert** [comment]
Thanks! Yeah, good question and not a great reason tbh. I rarely go below an H3 actually and really wanted to use the Things blue for my primary headers when writing (H2 and H3). The H2 has the underline differentiator (and size) and so I felt comfortable using the blue again for the H3. I may add a style settings option to change header colors in the future!

**Comment by colineckert** [comment]
Pushing an update shortly that will support font & header color customization via the Style Settings plugin. Let me know if you have any issues updating your theme, thanks! :)
