### ISSUE TITLE
Please increase contrast between bg and font color in code blocks

### ISSUE THREAD

**Issue by cm0s2** [colineckert/obsidian-things#20]
Hello,

Could you please increase the contrast between tbe background color and font face color in `code`  tags (both inline and blocks)? I currently have to strain my eyes in order to be able to read text wrapped in code tags.

Obsidian with Things theme:
<img width="622" alt="Skärmavbild 2021-12-03 kl  09 11 08" src="https://user-images.githubusercontent.com/17103323/144568329-43d391a6-6b76-4946-bedc-fc0f26f3b969.png">

Things 3 actual:
<img width="716" alt="Skärmavbild 2021-12-03 kl  09 10 53" src="https://user-images.githubusercontent.com/17103323/144568362-f60b3c98-15c9-4a19-87ec-eb3844d2f89d.png">

Best regards

**Comment by colineckert** [comment]
Thanks for raising this! I agree, the default code text is red but I've never been a fan. I'll work on this!

**Comment by colineckert** [comment]
This has been updated in the latest release. Updated the theme and let me know if you have any other issues. Thanks again!!

**Comment by cm0s2** [comment]
It looks great now, thanks a lot!

**Comment by eryajf** [comment]
Why do I still have this problem

**Comment by colineckert** [comment]
Hmm not sure. Have you updated your theme recently?

**Comment by eryajf** [comment]
> Hmm not sure. Have you updated your theme recently?

Yes, in order to confirm that it is the latest version, I have uninstalled and reinstalled the theme.
