### ISSUE TITLE
Scroll to top issue with long documents in Preview mode

### ISSUE THREAD

**Issue by KingOfSpades** [colineckert/obsidian-things#21]
Hey Hey,

Love the theme! Great effort. I noticed this theme seems to have the issue described over at: https://forum.obsidian.md/t/triggering-preview-mode-in-long-docs-causes-preview-to-scroll-to-top-of-document-in-certain-cases/13663/

When editing a long file (around 200 lines) and switching to preview the editor scrolls almost all the way to the top. When returning to edit mode the position is correct again. This is not strange since this theme has been based on the Minimal Theme and the same problem is being described in the thread https://forum.obsidian.md/t/triggering-preview-mode-in-long-docs-causes-preview-to-scroll-to-top-of-document-in-certain-cases/13663/2

Are more people experiencing this problem?

**Comment by AiYuE0** [comment]
> Hey Hey,
> 
> Love the theme! Great effort. I noticed this theme seems to have the issue described over at: https://forum.obsidian.md/t/triggering-preview-mode-in-long-docs-causes-preview-to-scroll-to-top-of-document-in-certain-cases/13663/
> 
> When editing a long file (around 200 lines) and switching to preview the editor scrolls almost all the way to the top. When returning to edit mode the position is correct again. This is not strange since this theme has been based on the Minimal Theme and the same problem is being described in the thread https://forum.obsidian.md/t/triggering-preview-mode-in-long-docs-causes-preview-to-scroll-to-top-of-document-in-certain-cases/13663/2
> 
> Are more people experiencing this problem?

Yes, I'm confused with the problem now. I have tried every given methods in the given link above but gain no effort.
