### ISSUE TITLE
Filename of embedded files is cut off

### ISSUE THREAD

**Issue by aventuraviper** [colineckert/obsidian-things#22]
When embedding a file within a note using `![[Filename]]`, the lower portion of the filename is cut-off when rendered in preview mode.
For example:
 ```
## Tasks
![[Today's Tasks]]
```
Renders like this:
![image](https://user-images.githubusercontent.com/55485055/145019377-21899b15-66e6-49d6-8646-ce7b3a10b661.png)

**Comment by colineckert** [comment]
Hey, thanks for raising this issue! I am releasing an update tonight that should address this, so closing for now. Please feel free to re-open if it's not solved on your end. Thanks again!
