### ISSUE TITLE
Gif for selecting LP/Reading mode in Title Bar not present on iPadOS

### ISSUE THREAD

**Issue by davebhc71** [colineckert/obsidian-things#23]
Unable to select between Live View and Preview (titles of the views change so frequently I may be using the name ‘of the day’) in Theme. Gif’s not present in Title Bar on iPad.
![IMG_0414](https://user-images.githubusercontent.com/80698092/145709192-cc7c01da-6ce8-4b38-8574-d38bc585737a.jpeg)

**Comment by KiloNiner** [comment]
Press the blue button in the lower right to cycle between preview and edit modes.

**Comment by colineckert** [comment]
Thanks, @KiloNiner!

Does that solve the issue for you, @davebhc71 ?
