### ISSUE TITLE
Vim insert mode landing on incorrect position

### ISSUE THREAD

**Issue by 23727** [colineckert/obsidian-things#24]
see: 
- https://forum.obsidian.md/t/vim-mode-i-command-cursor-insert-position-is-wrong/28112/4
- https://github.com/kepano/obsidian-minimal/issues/58

**Comment by colineckert** [comment]
Hey @23727 are you experiencing this issue anymore? It should have resolved itself with the release of Obsidian v1 and Things v2. I have been using vim mode for some time and am not experiencing issues, so closing this issue. Feel free to reopen if you find any bugs. Cheers!
