### ISSUE TITLE
select height

### ISSUE THREAD

**Issue by YangFong** [colineckert/obsidian-things#25]
> I don't know English; please excuse typing errors.

I found that the text of the selection box could not be displayed completely.I removed the height style of 1762 lines myself to restore normal display,

![image](https://user-images.githubusercontent.com/70502828/146003174-2f13e97e-d377-4144-a947-966cdf0a9af4.png)

![image](https://user-images.githubusercontent.com/70502828/146003187-19e79551-2127-4054-803b-ed31c622a577.png)

![image](https://user-images.githubusercontent.com/70502828/146003198-78e61508-c9fc-4f39-a184-8a0d470106ca.png)

**Comment by colineckert** [comment]
Awesome, great catch and thank you for raising this issue! I made this fix and am releasing an update tonight addressing this. I'll go ahead and close for now but please let me know if it's not addressed on your end. Thanks again!

**Comment by YangFong** [comment]
> Awesome, great catch and thank you for raising this issue! I made this fix and am releasing an update tonight addressing this. I'll go ahead and close for now but please let me know if it's not addressed on your end. Thanks again!

I used the new version, the problem was fixed,

---

Among other things, I noticed that the version number in the comment was not updated.

![image](https://user-images.githubusercontent.com/70502828/146167591-2ec610ce-2b34-4640-9fdf-71948a657ab8.png)
