### ISSUE TITLE
code indentation

### ISSUE THREAD

**Issue by YangFong** [colineckert/obsidian-things#26]
Hi, I noticed some indentation issues with the code block in the edit area.

![image](https://user-images.githubusercontent.com/70502828/146309098-b260e277-71ae-4329-b19a-1493d2e83c8c.png)

By default, it looks like this.

![image](https://user-images.githubusercontent.com/70502828/146308913-29abeb36-2981-4fbd-a202-c84f67492f06.png)

If possible, please tell me the reason.

**Comment by colineckert** [comment]
Thanks for creating this issue! I just published a new update that solves this issue. 

Closing the ticket for now, but feel free to reopen it if it's not working for you. Thanks!

**Comment by YangFong** [comment]
@colineckert That problem is gone. Success
