### ISSUE TITLE
OK! this bug should now be fixed in the latest release. Update your theme and let me know if the font size slider doesn't work! Closing for now :)

### ISSUE THREAD

**Issue by sakura-he** [colineckert/obsidian-things#27]
Changing the font size in Settings -> Appearance has no effect, the font size in preview as a whole remains the same.but font-size in edit mode is changed

Applies for desktop 0.13.14. Theme version is latest

**Comment by bjorndotwork** [comment]
I can confirm it's still having no effect for me in reading view, confirmed latest version of theme and latest non-Insider version of Obsidian.

**Comment by astutecat** [comment]
This issue still is present for mobile -- at least on iOS.

**Comment by colineckert** [comment]
I just pushed an update yesterday. Can you try now and see if the font size slider in "Appearance" is working?

**Comment by astutecat** [comment]
Yep, the font size is consistent, thanks!
