### ISSUE TITLE
Live Preview - Check Box Color Inconsistency

### ISSUE THREAD

**Issue by SamuelYancy** [colineckert/obsidian-things#29]
Currently with the new Live Preview feature, the Things Theme does not render the blue colored check boxes. It renders them in the default obsidian purple color. It only changes to the blue check box if you take the page out of edit mode.

Live Preview - Edit Mode
![CleanShot 2021-12-28 at 11 45 53](https://user-images.githubusercontent.com/62109721/147593018-edcff9be-c70a-404d-ac08-339e765a45b4.png)

Read Mode
![CleanShot 2021-12-28 at 11 45 14](https://user-images.githubusercontent.com/62109721/147592958-d2b75c9a-a158-4019-8415-8611f9b1a674.png)

I would love to get the blue check marks to be the color in the live preview edit mode.

**Comment by SamuelYancy** [comment]
It looks like you pushed an update on this yesterday! It looks great, thanks!

![image](https://user-images.githubusercontent.com/62109721/148946686-a427f08f-8d2d-47d0-a411-79d0793891c5.png)

**Comment by colineckert** [comment]
Awesome! Thanks for sharing the issue and for using Things!!
