### ISSUE TITLE
Honestly Beautiful

### ISSUE THREAD

**Issue by Calhistorian** [colineckert/obsidian-things#3]
Love the aesthetics a great deal. 

I would argue only one small problem. The gutter is too small on the left margin (and I would assume the right as well). Importantly, access to collapse carrots is hidden. It is possible its a plugin conflict, but I don't use any plugins that alter the gutter (that I know of)

<img width="508" alt="CleanShot 2021-11-05 at 07 14 31@2x" src="https://user-images.githubusercontent.com/51142180/140524304-b475ff6f-9e47-4808-80f9-101740e88155.png">

**Comment by colineckert** [comment]
@Calhistorian yuck, great catch! I'll get to work on a patch asap and post here when it's ready for you to update. Thanks for bringing to my attention and glad you like the aesthetic!

**Comment by colineckert** [comment]
@Calhistorian patch has been pushed and published v1.2.2 with added padding for the gutter. Please let me know if this addresses the bug you found and I will close this issue. Thanks!

**Comment by Calhistorian** [comment]
I am on a different monitor now (though it still had the problem, and now it looks great. Very clean interface. 

<img width="228" alt="CleanShot 2021-11-05 at 09 16 30@2x" src="https://user-images.githubusercontent.com/51142180/140543446-11862a2b-aa71-4bb2-994a-354558fce744.png">

I have another request but I will make another issue.

**Comment by colineckert** [comment]
Awesome! closing this issue and yes, keep them coming!
