### ISSUE TITLE
[BUG] #todo in H1 Title size is inconsistent

### ISSUE THREAD

**Issue by OGALI** [colineckert/obsidian-things#30]
When making an H1 title in **live Preview**, tags have inconsistent sizing.

![image](https://user-images.githubusercontent.com/33200146/147704647-a82e77c0-32e6-4922-88f0-2ea91233369f.png)

**Comment by ahmetasabanci** [comment]
I'm also having this issue with tags in any level of H titles.

Although I also noticed that this happens with other themes too, I wonder if it's because something has changed behind the scenes with the Live Preview because it started to happen for me after the first Live Preview update.

**Comment by colineckert** [comment]
Hi, thanks for submitting this issue! I just published a new release that should address this bug. 

I'll close the issue for now, but feel free to reopen if it's not resolved for you.

Thanks again and thanks for using Things!
