### ISSUE TITLE
[FEATURE] Option to disable bottom-right view mode button on mobile

### ISSUE THREAD

**Issue by bjorndotwork** [colineckert/obsidian-things#31]
First of all, I *love* this theme. Thank you for making it.

That said, I would like the “quick preview/edit” button in lower right on mobile to be optional, since it goes against my mental expectations for such a button which typically means compose new document in most other apps. And, ideally, to have the option of making that button actually function as a “quick new note” button.

**Comment by colineckert** [comment]
Thanks so much for the support and for creating this feature request! 

I too would love to swap that button for a "new note" function - might create a plugin in the near future to do just that! In the meantime, I've just released an update for the Style Settings plugin to allow toggling the floating-action button.

Let me know if you have any issues and I'll reopen this ticket. Thanks so much!
