### ISSUE TITLE
The font size is too large on the mobile reading view

### ISSUE THREAD

**Issue by Gnblink0** [colineckert/obsidian-things#32]
Thanks for contribution!This theme is very good-looking.
But I found it seems that the font size is too large in the mobile reading view.It's normal on pc.
![529922b30a37c742efdf67c9d7afcaf](https://user-images.githubusercontent.com/90372670/147761339-a093553d-49fe-4384-870e-72be2b3350c5.jpg)
![464bb2aa64916bd5b24c76daeb3cc94](https://user-images.githubusercontent.com/90372670/147761363-c96ea3ed-5c32-4692-aa73-e9fb217d7676.jpg)

ipad pro2020 ; obsidian1.0.5

---
I read the history and noticed that you claimed  this problem had been solved on November 6, but obsidian reminded me that this theme has been updated but this problem still exists.

**Comment by astutecat** [comment]
I also have this issue at the moment.

**Comment by kevinawoo** [comment]
Same, but my partial solution was to install Styles Settings and set the font size to be 6.5em

This isn't really a fix as the setting ends up syncing to the desktop as well. So either I reset it constantly between devices or disable syncing. 

It would be great if there's an mobile only font size  setting.

**Comment by colineckert** [comment]
Closing this issue as it is no longer relevant since Obsidian v1. Cheers!
