### ISSUE TITLE
Rendering A Double Bullet - Live Preview

### ISSUE THREAD

**Issue by SamuelYancy** [colineckert/obsidian-things#34]
It looks like the live preview is rendering some bullets two times next to each other.

![image](https://user-images.githubusercontent.com/62109721/149175019-c4d38c3b-c625-4216-8307-87bda864fdb0.png)

This goes away when you go into Reader Mode

![image](https://user-images.githubusercontent.com/62109721/149175160-c95b244c-58ab-49e9-9022-3b09e745dc14.png)

When I disable the Things Theme and just use the base Obsidian theme, this doesn't occur.

Live Preview
![image](https://user-images.githubusercontent.com/62109721/149175359-663a1632-cd3e-4de6-89ff-763ba2ef98cc.png)

Reader Mode
![image](https://user-images.githubusercontent.com/62109721/149175473-c1e6fb20-f7e1-4f03-8a49-df2977babf30.png)

**Comment by lukthony** [comment]
I am also experiencing this issue.

**Comment by colineckert** [comment]
Hi, thanks for submitting this issue! I just published a new release that should address this double-bullet bug. 

I'll close the issue for now, but feel free to reopen if it's not resolved for you.

Thanks again and thanks for using Things!

**Comment by SamuelYancy** [comment]
Updated the theme and it is fixed!

Thanks so much!

**Comment by lukthony** [comment]
This works for me now as well. Favorite theme, thanks for your work. Cheers.
