### ISSUE TITLE
[Bug] [Android] Floating Edit/Preview icon is blocked by Advanced Mobile Toolbar Plugin

### ISSUE THREAD

**Issue by the0s0ph1st** [colineckert/obsidian-things#36]
As mentioned on the title the floating icon to the bottom right is blocked when using Advance Mobile Toolbar of at least 2 rows high.

![Screenshot_20220113-193534](https://user-images.githubusercontent.com/40872841/149447648-2169184c-1ce3-4773-9288-b5d425ff9e78.jpg)

I don't use it a lot and if needed I already made a Mobile toolbar button for it, but aesthetically it does not look good.

Cheers! Things is a really great theme, keep up the good work!

**Comment by colineckert** [comment]
Thanks for creating this issue! I just released an update that addresses this issue (the current solution is a bit WIP still, as the button now sits a bit higher when the keyboard is closed). 

I've also added the ability in the style settings plugin to toggle the floating button if needed. 

Let me know if you have any issues and I'll reopen this ticket. Thanks!
