### ISSUE TITLE
Bullet Points are quite low

### ISSUE THREAD

**Issue by rarfell** [colineckert/obsidian-things#37]
Firstly really want to thank you for this amazing theme - very well put together.

Am a little bit irked only by the position of the bullet points, which seems to be deviated quite low, and not centralised vertically (only in the editing view) - would be great if this could be fixed!

This issue seems to differ according to font size too - the larger it is the higher up the bullet point will go.

**Comment by colineckert** [comment]
Hey, thanks for creating this issue! Do you mind sharing a screenshot of what you're seeing? On my end, the Things-theme bullets seem to be aligned with the positioning in the default theme and others. Is this specific to Live Preview or the older Reading mode? 

Thanks for using the theme and the kind words!

**Comment by colineckert** [comment]
Closing this issue as it is no longer relevant since Obsidian v1 and Things v2. Cheers!
