### ISSUE TITLE
Todoist bullet colour missing in Live Preview

### ISSUE THREAD

**Issue by aventuraviper** [colineckert/obsidian-things#38]
Hi

The obsidian todoist plugin just received an update to resolve some live-preview rendering issues. As a result I believe some of the CSS classes may have changed and so the theme doesn't render the blocks as it should do in live-preview. Reading mode is unaffected.

https://github.com/jamiebrynes7/obsidian-todoist-plugin/issues/138#issuecomment-1016863577

Reading Mode
![Reading Mode](https://user-images.githubusercontent.com/55485055/150294534-a97e1fac-defc-4226-aef4-3f216aaee5ea.png)
Live Preview
![Live Preview](https://user-images.githubusercontent.com/55485055/150294630-437f00f3-747f-4a5a-8a0f-048b2038cf38.png)

**Comment by colineckert** [comment]
Thanks for creating this issue! I just released an update that should fix this.

Closing this issue, but feel free to reopen if it is not working for you. Thanks!
