### ISSUE TITLE
Adaptation problems with the Outliner plugin in the new Live Preview mode

### ISSUE THREAD

**Issue by williamlorder** [colineckert/obsidian-things#39]
Hi, thank you for developing such an excellent theme. However, I noticed that the vertical line for the outline disappeared in the new version of the theme with the outliner plugin. I remember that in the old version when using Outliner the vertical lines would appear. You can see the picture below.

<img width="743" alt="150365928-3822e55f-813f-4131-bc64-63b5443b4e60" src="https://user-images.githubusercontent.com/83387569/150366520-d2150ef3-47b1-4f83-ba49-1ec41f8ff09d.png">
The vertical lines under the original theme can be displayed, please see the image below
<img width="743" alt="150366122-2729e590-768c-4386-948e-60cd72d83009" src="https://user-images.githubusercontent.com/83387569/150366649-6aa111d5-8a5e-447f-9a73-8188c99cd939.png">

**Comment by franciskafieh** [comment]
I'm having this issue as well.

**Comment by franciskafieh** [comment]
Obsidian now has these lines built-in. Feel free to close this issue :)
