### ISSUE TITLE
Grab Handle for Pane Resizing 

### ISSUE THREAD

**Issue by Calhistorian** [colineckert/obsidian-things#4]
This is one of the biggest things that turns me off from a theme (not that you should care what I require - just my observation). That is when for whatever reason the resizing handles get shrunken down significant to 1-2px - where in the default theme it is at least 2-4px. And given the significance of pane management in Obsidian, this has in my opinion a huge impact on usability. I am sure it will inevitably increase the border, but that is the way it goes. Thanks again, Great theme.

<img width="2585" alt="CleanShot 2021-11-05 at 09 22 44@2x" src="https://user-images.githubusercontent.com/51142180/140544215-72331341-aca9-4911-a9a2-f0351ebf5fa2.png">

**Comment by colineckert** [comment]
@Calhistorian thanks for sharing this feedback. I can make the pane handle size a little larger to help you while keeping the minimal aesthetic. Will find the right balance and let you know when it's updated. Thanks!

**Comment by colineckert** [comment]
Ok, I increased the hover size of the pane resize handle. Should make it a bit easier to manage your panes. Let me know if this helps and I'll close the issue. Thanks, again!
