### ISSUE TITLE
Support for cssclass: numbertable

### ISSUE THREAD

**Issue by richardlm** [colineckert/obsidian-things#40]
Hi

Would you be able to add support for automatic row numbering of tables?

Yin & Yang does this with `cssclass: numbertable` in frontmatter.

Thanks,
Richard

**Comment by colineckert** [comment]
Great idea, thanks for opening an issue! 

I've added support for `numbertable` as well as `color-rows` CSS classes.

I've released a new version with these updates, so closing this issue but feel free to reopen if it is not working for you.

Thanks!
Colin
