### ISSUE TITLE
Floating Button Squashed in Sliding Panes on Tablet

### ISSUE THREAD

**Issue by keithadams** [colineckert/obsidian-things#41]
I'm using Obsidian on a Kindle Fire HD 10

<img src=https://user-images.githubusercontent.com/11220719/151632116-ad0e4c78-32a3-419b-a814-986f5d9dc434.png width=50% height =50% />

**Comment by colineckert** [comment]
Hey @keithadams, are you still experiencing this issue since Obsidian v1 and Things v2 were released? If not, can you pls close this issue? Thanks!

**Comment by keithadams** [comment]
I no longer have the device to test with but I'll close the issue.
