### ISSUE TITLE
MOBILE

### ISSUE THREAD

**Issue by hyurpg** [colineckert/obsidian-things#45]

**Comment by hyurpg** [comment]
thanks for your theme, its very grace, but in mobile, when i in editor mode inputing , the left padding is too narrow

**Comment by hyurpg** [comment]
![2583ab7e8d260b8146ca17900047086](https://user-images.githubusercontent.com/18240850/153802710-852f3be5-d43c-48ad-b895-88df4d75aeb8.jpg)

**Comment by colineckert** [comment]
Thanks for creating the issue! Can you try enabling "Readable line length" under the Editor settings? Does doing so fix this issue for you?

**Comment by hyurpg** [comment]
> Thanks for creating the issue! Can you try enabling "Readable line length" under the Editor settings? Does doing so fix this issue for you?

If I enabling "Readable line length"，in read view，the length is too narrow。Is it possible to keep a suitable width for both left and right when editing and reading？Thank u
![b7c0e2d8b2b88b8ee42b91d3bf354fa](https://user-images.githubusercontent.com/18240850/153806856-9ab88618-4b5a-494b-86d2-8e5a0ce61d08.jpg)

**Comment by colineckert** [comment]
Closing this issue as it is no longer relevant since Obsidian v1. Cheers!
