### ISSUE TITLE
Why the H4 heading is capital ，both coding mode and preview mode

### ISSUE THREAD

**Issue by Darkluna999** [colineckert/obsidian-things#46]

**Comment by colineckert** [comment]
Hi, thanks for creating the issue. This was purely a stylistic decision to give the H4 more distinction, as the H4 size is similar to regular text. 

If you'd like to change it to the default case, just comment out this line in your local Things them CSS file: https://github.com/colineckert/obsidian-things/blob/main/obsidian.css#L627

Thanks!
