### ISSUE TITLE
macOS buttons are obscuring  the note title

### ISSUE THREAD

**Issue by manuelhubacher** [colineckert/obsidian-things#47]
I’ve encountered a small nuisance when I try to combine this theme and the [Hider plugin](https://github.com/kepano/obsidian-hider) (Version 1.1.1). When ‘Hide title bar (frameless mode)’ and ‘Hide app ribbon’ are turned on in Hider, the macOS buttons are obscuring the note title in small windows with multiple notes open.

<img width="1072" alt="Bildschirmfoto 2022-02-18 um 14 07 01" src="https://user-images.githubusercontent.com/17408325/154734036-ee0fd7c0-8478-4d19-b4ee-1feabd37d4d2.png">

- macOS 12.2.1
- Obsidian 0.13.24

**Comment by 702573n** [comment]
Furthermore the translucend window is broken on hiding titlebar (frameless mode) with hider plugin.
<img width="378" alt="Bildschirmfoto 2022-07-02 um 08 04 34" src="https://user-images.githubusercontent.com/59178587/176988813-dee010df-b065-4a65-9b08-5e1bf318aa94.png">

**Comment by colineckert** [comment]
Hi! I have fixed the original issue @manuelhubacher and you should now see it reflected in your latest theme once updated.

Looking into the translucent window issue next @702573n, thanks!
