### ISSUE TITLE
Ligatures not working

### ISSUE THREAD

**Issue by Pixouls** [colineckert/obsidian-things#48]
Hi I'm a bit of a tech noob so please bear with me.
-> is not turning to → for me, it appears this is an issue with ligatures when I went to the obsidian forum, but the description for the theme says ligatures should be supported.

When I use other themes like California Coast or Sanctum either, if that matters.
I remember I've gotten them to work on Obsidian for me in the past so I'm not sure why I haven't been able to have them work in recent months.

**Comment by mr-wunderlich** [comment]
Ok, seems like the JetBrains font was missing locally, so installing that solved the issue for me.

**Comment by hsiktas** [comment]
The default theme is using the Inter font, which provides these ligatures. You can manually add it in the Style Settings plugin at the beginning of the fonts list.

**Comment by colineckert** [comment]
Thanks, @hsiktas for clarifying! Yes, Things uses `-apple-system` font, which does not feature ligatures in edit or preview mode (non-code, which uses JetBrains). If you'd like to have ligatures outside code, I'd also recommend using Inter font (featured in the default theme) as it's very similar, and adding to the beginning in Style Settings. Thanks!
