### ISSUE TITLE
Headings sizes in edit and preview modes

### ISSUE THREAD

**Issue by gdigesu** [colineckert/obsidian-things#5]
Hi @colineckert !

Very nice theme! Congratulations.

Size of headings in edit mode are quite different from their size in preview mode.
How can I make the edit mode size match the preview mode size?

### Edit mode
---
![Screenshot 2021-11-05 at 13 22 23](https://user-images.githubusercontent.com/44509843/140544238-ec386e0b-44c6-4c1d-83a8-cfa2cd6e3880.png)

### Preview mode
---
![Screenshot 2021-11-05 at 13 22 42](https://user-images.githubusercontent.com/44509843/140544389-cf4194d4-37e2-4a08-9d18-a4ca2823c727.png)

**Comment by colineckert** [comment]
@gdigesu thanks for raising the issue! This is something I noticed as well - it seems to be mobile-only - and I'm currently working on a fix. I should have a patch update ready later today.

**Comment by colineckert** [comment]
@gdigesu ok this bug should be fixed - sizing is consistent on mobile between edit and preview modes. I just published a new release, so update your theme and let me know if this issue persists. Thanks again!

**Comment by gdigesu** [comment]
Collin, thank you.
