### ISSUE TITLE
Punctuation marks doesn't work properly

### ISSUE THREAD

**Issue by pascowl** [colineckert/obsidian-things#50]
Hi,

When I quote a sentence and use the punctuation marks (like quotation, apostrophe etc.) I realized that it doesn’t work properly with this theme. Even when you export a document as a pdf by the theme’s style, the marks seem straight on the exported document.

I think this is a general typographic problem which is releated with the font itself. I decided to create a post Obsidian's forum about this issue. For more detail, plese [check here](https://forum.obsidian.md/t/punctuation-marks-doesnt-work-properly-with-some-community-themes/33777). I attached a screenshot file as an example from [this article](https://typographyforlawyers.com/straight-and-curly-quotes.html).

![quotes](https://user-images.githubusercontent.com/96392310/157719428-6265d52c-0c12-4692-a384-f13dbcfbf223.png)

How we could figure it out this issue? Thank you for create this beautiful theme.

**Comment by jasonho1308** [comment]
You can change the font to the one you wanted to use with [style setting plugin](obsidian://show-plugin?id=obsidian-style-settings)

![image](https://user-images.githubusercontent.com/50993239/161768512-69a11a35-c431-45f3-802d-38c5c52c5884.png)

**Comment by pascowl** [comment]
> You can change the font to the one you wanted to use with style setting plugin
> 
> ![image](https://user-images.githubusercontent.com/50993239/161768512-69a11a35-c431-45f3-802d-38c5c52c5884.png)

Thanks for the suggestion. Now I could set my personal font settings with the [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) plugin.
