### ISSUE TITLE
Adding another font

### ISSUE THREAD

**Issue by dcoales** [colineckert/obsidian-things#52]
I like the font used in the Sanctum theme 'IBM Plex Sans *' but prefer the rest of this theme.  I tried typing this into the fonts section in Style Settings but it had no effect - I expect this font has to be added somewhere and I just don't know how to do that.  

Would it be possible to make that font available in the theme (or point me in the direction of some instructions as to how I could do it myself).

Many thanks,
David

**Comment by colineckert** [comment]
Hey David, thanks for creating an issue. Do you have the IBM Plex Sans font installed on your machine? If so, you should be able to add it to the front of the font input like so:

<img width="307" alt="Screen Shot 2022-03-31 at 9 32 25 AM" src="https://user-images.githubusercontent.com/60206665/161105342-07ab86e7-d477-4b44-b942-3d96daf9e83c.png">

Let me know if that solves it for you!

**Comment by dcoales** [comment]
I've finally managed to figure out how to include a google theme via a snippet so it seems to be working now.  Thanks.

**Comment by nine9ths** [comment]
> If so, you should be able to add it to the front of the font input like so:

Hi, I'm new to Obsidian and have a similar issue—I'd like to add a font, but not sure where the "font input" field you referred to can be found. Can you point me to where I would find this? As the OP said it doesn't appear to be in Options > Appearance > Font

Thanks!

**Comment by colineckert** [comment]
Hi @nine9ths - happy to help! The font input referenced in the screenshot above is actually within the Style Settings plugin settings, so you'll first need to install that plugin and then select it from your options navbar to find the theme font settings (Style Settings > Things Theme > Fonts).
<img width="1016" alt="Screen Shot 2022-04-17 at 8 47 56 PM" src="https://user-images.githubusercontent.com/60206665/163751469-d855cfb2-cdc0-4a19-9b61-5a4838284b1e.png">

Again, just make sure the font you're adding is installed on your device. Hope this helps!
