### ISSUE TITLE
Scroll bars lack UI

### ISSUE THREAD

**Issue by visualcurrent** [colineckert/obsidian-things#53]
Wonderful theme!

Can anyone else see the scroll bars but not be able to mouse them in any way?

I'm using the default v1.7.0, with no style changes. Fonts removed from style settings and added with new Obsidian settings. But I don't think that affects it, just reporting all I have modified.

**Comment by 469698742** [comment]
I can see the scroll bars of font size，but no size change after adjustment. Besides, using the `Ctrl + Scroll` do not work.
