### ISSUE TITLE
outline alignment problem

### ISSUE THREAD

**Issue by joonhyuk** [colineckert/obsidian-things#54]
<img width="556" alt="스크린샷 2022-04-05 오후 2 13 33" src="https://user-images.githubusercontent.com/6174121/161683609-e0cc962c-d840-459a-9f2f-e7a9f5989cef.png">

Hi,
Seems to be an alignment error of outline panel(core plugin of Obsidian)

Thanks!

macOs v12.3
Obsidian v0.14.2
Things (2022-04-05 updated)

**Comment by ZJsheep** [comment]
Same problem for me!

**Comment by colineckert** [comment]
Thanks for creating this issue! This has been fixed in the latest release (v1.7.2). Let me know if you have any issues. Cheers!
