### ISSUE TITLE
Font size adjustment not working for me (using latest version of Things)

### ISSUE THREAD

**Issue by richardlm** [colineckert/obsidian-things#55]
Hi

I know there have been a few issues raised about font size adjustment and it is now meant to be fixed, but it does not work for me.

The 'Font Size' slider under 'Appearance' has no effect at all on the Things theme, and I cannot see a setting in 'Style Settings' that changes the main font size. There is an entry for the sidebar and tag font size that works, but not the main text on a page.

The 'Font Size' slider works on the Default theme nicely in that it adjusts all elements appropriately.

I have disabled all plug-ins to check for any clash, but the problem still remains.

Any hints on how to debug this?

Thanks.

**Comment by PusheenMaster5** [comment]
I am having this problem too, it just started today for me. On windows 11 if that helps.

**Comment by PusheenMaster5** [comment]
I think it was an app update, i tried Things versions down to 1.6.8 and no downgrading fixed the problem

**Comment by SoldMeteor** [comment]
have same problem 🙋‍♂️

**Comment by colineckert** [comment]
Hey all! Yes, there was an app update that broke the font slider functionality for the theme. I pushed a quick fix for updating the overall font size via the Style Settings plugin (use Things v1.7.1). You can find it under Things Theme > Typography (default is `1em`) and use it to increase the font size in editor panes of all text (body & headers).

<img width="735" alt="Screen Shot 2022-04-12 at 10 14 31 AM" src="https://user-images.githubusercontent.com/60206665/163017653-db95ce1d-b263-4d59-a00d-60fa71c17445.png">
 
Working on getting the slider fixed asap. Thanks!

**Comment by sowenjub** [comment]
Thank you @colineckert for being so reactive, much appreciated! 🚀🤩🙌

**Comment by tildejustin** [comment]
I thought of this issue again and was comparing the code of minimal to things, and I found that in minimal the code for font-adaptive-normal is, `--font-adaptive-normal: var(--font-text-size);` , whereas in obsidian-things it's `--font-adaptive-normal: var(--font-normal);` and font-normal is hardcoded to 16px. If you use the minimal version in obsidian things, then font size is respected in settings again. I'm not very good at css so I don't know what why this was set like this, but it seem to fix the issue.

**Comment by tildejustin** [comment]
I had it working, but that was with a lot of styles disabled in the inspector so I can't reproduce it. I might report back tomorrow if I find a working fix.

**Comment by tildejustin** [comment]
` --preview-font-size: var(--editor-font-size);` has to be switched to ` --preview-font-size: var(--text-font-size);` as well

**Comment by tildejustin** [comment]
Change file extension to css and put in your snippets folder, should make font sizing work again. Very hacked together so someone might want to take a look at it. ([fontfix.txt](https://github.com/colineckert/obsidian-things/files/9260812/fontfix.txt))

**Comment by SheepTAOCN** [comment]
> Change file extension to css and put in your snippets folder, should make font sizing work again. Very hacked together so someone might want to take a look at it. ([fontfix.txt](https://github.com/colineckert/obsidian-things/files/9260812/fontfix.txt))

It's working now, thanks.

**Comment by colineckert** [comment]
Hey all, thank you so much for continuing to post in this issue thread, sharing tips with each other, and helping improve the theme. I've _finally_ fixed this issue and is live in the latest theme. Just update your Things theme and the font size slider should be working :) pls reopen the issue if you experience any bugs, thanks!
