### ISSUE TITLE
be able to change color of links

### ISSUE THREAD

**Issue by amandarito** [colineckert/obsidian-things#56]
hello,

I didn't see this feature in the theme settings. I was wondering if there is an option to change the color of links from the default blue. both for internal and external links. this is an example of the current links:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/44073711/164578908-a8a0f655-94a9-40c8-8457-1b2b4a6a00b2.png">

will this feature be added or already is? thanks

**Comment by colineckert** [comment]
Hi, thanks for opening this issue. It's a great idea! I added a slider to adjust the hue of the color of the links to the Style Settings plugin in the latest release (v1.7.2). Cheers!
