### ISSUE TITLE
Second cut off sync icon on mobile

### ISSUE THREAD

**Issue by hsiktas** [colineckert/obsidian-things#57]
Below the regular sync icon, I can see another cut-off one. Is this intentional or a bug?

![IMG_1887](https://user-images.githubusercontent.com/4571159/166110418-f1102495-47ae-4d3b-98c2-da777fc555f2.PNG)
![IMG_1891](https://user-images.githubusercontent.com/4571159/166110420-dfa7a804-39c3-471f-811a-dc2d9dfa37cb.PNG)

**Comment by colineckert** [comment]
Hey, @hsiktas thanks for catching! This has been fixed in the latest release of the theme. Cheers!
