### ISSUE TITLE
in macOS cmd+F search bar covers file content

### ISSUE THREAD

**Issue by BobWCB** [colineckert/obsidian-things#58]
<img width="797" alt="截屏2022-05-07 21 41 35" src="https://user-images.githubusercontent.com/13690533/167256959-b55abf9f-f41b-4264-bcfa-bb5fe0fa73e5.png">
<img width="799" alt="截屏2022-05-07 21 41 24" src="https://user-images.githubusercontent.com/13690533/167256962-b9b151ae-fd43-4f0a-8318-39150cc852f5.png">

**Comment by colineckert** [comment]
Great catch! This has been addressed in the latest theme version.

Thanks for creating the issue! Closing now, but please reopen if you have any issues. Cheers!
