### ISSUE TITLE
Settings to turn off underlined links not working?

### ISSUE THREAD

**Issue by terheyden** [colineckert/obsidian-things#59]
Hello,

I'm trying to turn off underlined links in the Style Settings, but it doesn't appear to have any effect? I tried restarting Obsidian. Anyone else having this issue? Obsidian v0.14.6.

![2205091619-things1](https://user-images.githubusercontent.com/984174/167513979-b9dbb237-54b7-481c-a189-37cf265ffda5.jpg)

![2205091619-things2](https://user-images.githubusercontent.com/984174/167513992-f84b4fbc-6e62-4052-b971-c856da3cb15b.jpg)

**Comment by colineckert** [comment]
Yeah, this appears to be an issue specific to Live Preview. This should now be fixed in the latest theme version!
