### ISSUE TITLE
Links without underline

### ISSUE THREAD

**Issue by gdigesu** [colineckert/obsidian-things#6]
Hi @colineckert  !

Would you consider showing links - internal and external - without the underline?

**Comment by colineckert** [comment]
I would! I go back and forth on this myself. I am working on support for the Style Settings plugin and will include underline/no underline toggle options for both internal and external links. I should have this in the next release, expected to publish by tomorrow. Thanks!

**Comment by gdigesu** [comment]
Colin, hi.

You're always very kind.
Responsiveness is key these days and you demonstrate it.

Kind regards,

Giovani di Gesù
https://gdigesu.envision.consulting
https://directions.envision.consulting
Main +55(11)3042-8860
***



On 9 Nov 2021, at 15:48, Colin Eckert ***@***.***> wrote:

﻿

I would! I go back and forth on this myself. I am working on support for the Style Settings plugin and will include underline/no underline toggle options for both internal and external links. I should have this in the next release, expected to publish by tomorrow. Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcolineckert%2Fobsidian-things%2Fissues%2F6%23issuecomment-964434507&data=04%7C01%7Cgdigesu%40envision.consulting%7C0efbfffaf2ec4b6828d608d9a3b17acf%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C637720804979939047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t12F4okkmS4arIZzJZSfWEzic7IazF58u%2Bcd2uRo3%2BQ%3D&reserved=0>, or unsubscribe<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTSVE6C25HCYINBJXJCZPTULFUF5ANCNFSM5HQ45JFA&data=04%7C01%7Cgdigesu%40envision.consulting%7C0efbfffaf2ec4b6828d608d9a3b17acf%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C637720804979949000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F72KZN%2BxkpIW%2BbylqZ8eERjNeV0gzbcDzvH9LZwNDug%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgdigesu%40envision.consulting%7C0efbfffaf2ec4b6828d608d9a3b17acf%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C637720804979949000%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SKlEkW%2FkFax0Lvj5oqvXEn7JWqcIkKxlETgzrTTrl4Y%3D&reserved=0> or Android<https://bra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgdigesu%40envision.consulting%7C0efbfffaf2ec4b6828d608d9a3b17acf%7C718f3212162b4bf891c55c06573e715e%7C0%7C0%7C637720804979958956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ebwZKfSHsFiC8GL1%2BOWTRAAzoQl6T3Hatpq0cf%2F8C%2FU%3D&reserved=0>.

**Comment by colineckert** [comment]
I want to make sure I am responsive to those that are kind of enough to use my theme, let alone take the time to share feedback. Thanks :)
