### ISSUE TITLE
Feature request: change link color?

### ISSUE THREAD

**Issue by terheyden** [colineckert/obsidian-things#60]
In Style Settings it looks like the link hue can be changed, but it would be really nice if we could also pick the link color. Thanks for the consideration.

**Comment by colineckert** [comment]
Hey @terheyden - changing the hue will in fact change the color. The theme's CSS uses [HSL](https://www.w3schools.com/colors/colors_hsl.asp) colors, and the hue is the degree on the color wheel from 0 to 360. 0 is red, 120 is green, and 240 is blue.

Give it a try and let me know if that works for you! Closing this issue but feel free to reopen it if you have more questions. Thanks!

**Comment by jandamm** [comment]
@colineckert while you can change the tint of the link with this setting. But you cannot change how prominent the link appears.

For me a link looks too pale and I confuse it with a link to a non-existing file all the time. (Not when seeing two next to each other but when only seeing a link)
