### ISSUE TITLE
Hi there, the upper right corner of the code block is partly obscured.

### ISSUE THREAD

**Issue by imingx** [colineckert/obsidian-things#62]
In the macOS Obsidian v0.14.6:

<img width="251" alt="image" src="https://user-images.githubusercontent.com/54981719/168962066-d0f279fa-0e6c-403a-a610-320dab2df320.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/54981719/168962340-ebc5797f-e987-41b5-9a4d-b11e929f23eb.png">

**Comment by colineckert** [comment]
Good catch! This has been addressed. Update your theme and you should see it fixed. Thanks!

**Comment by imingx** [comment]
It has been fixed. Thanks!
