### ISSUE TITLE
status bar padding issue

### ISSUE THREAD

**Issue by Aneeqasif** [colineckert/obsidian-things#67]
the progressbar from day planner is not oriented right. it works fine with other themes

![image](https://user-images.githubusercontent.com/78728701/176917874-e23817ff-dc95-40d9-92e1-339c32046118.png)

**Comment by colineckert** [comment]
Hi, this should now be fixed! Thanks for creating the issue :)

**Comment by Aneeqasif** [comment]
can you please point me to commit that fixes this

**Comment by colineckert** [comment]
Here is the commit and where the specific change, as well as how it is working on my end: 
https://github.com/colineckert/obsidian-things/commit/a83a429b614807e90c4335c34e74cf79ee9ae560#diff-d8fa52010b46704cc3fe21d37cbde6b9f9298154b3d971a076b06a9a95f15560R5622-R5635

<img width="546" alt="Screen Shot 2022-07-08 at 8 56 11 AM" src="https://user-images.githubusercontent.com/60206665/178027898-19c1f2c7-e6b8-4576-b32e-8dd7797057e3.png">
