### ISSUE TITLE
Sandwich menu button on Mobile

### ISSUE THREAD

**Issue by wedgiebee** [colineckert/obsidian-things#70]
Suggestion: When in note view, it would be awesome to have the option to show a sandiwch menu button in the top-left corner to open the file explorer! I appreciate the minimalism of not having that there, but sometimes I get disoriented with a button there and it takes a moment to remember I need to swipe for that functionality.

**Comment by Jaques22** [comment]
Yes, i agree. On my phone a swipe from the left of the screen goes back a page so it is a fine line between opening the menu and going back a document. Would much prefer the sandwich button back

**Comment by Jaques22** [comment]
This snippet re-adds the sandwich menu:
```
.is-mobile .view-header .view-header-icon .three-horizontal-bars {
  opacity: 1;
  display: revert;
  transform: scale(1.4);
}
.is-mobile .view-header-icon {
	opacity: 1;
	display:revert;
	padding: 0px 15px !important;
	top: 5px;
 }
.is-mobile .view-header .view-header-title-container{
	left: 60px;
}
```
It might not be the most efficient way to do it but it's what i've come up with. Could be added as a Style Settings option. May create a PR

**Comment by wedgiebee** [comment]
This is awesome!
