### ISSUE TITLE
Mobile back button

### ISSUE THREAD

**Issue by jandamm** [colineckert/obsidian-things#77]
Thanks for this nice theme.
I really like the floating button in the mobile version.

I wanted to ask if it's possible to add a floating button to go back to the previous note?
I find this really cumbersome to do in the iPhone version of Obsidian.

**Comment by colineckert** [comment]
hey @jandamm have you updated your Obsidian app to v1? They added back/forward buttons to the UI which I think solves this need. So closing this issue, but feel free to reopen if there is more you're looking for. thanks!

**Comment by jandamm** [comment]
Yes, v1.0 is really nice.
This solves the issue 👍
