### ISSUE TITLE
The full screen button for left sidebar items like Search is missing

### ISSUE THREAD

**Issue by GitMurf** [colineckert/obsidian-things#8]
I like to go to full screen when looking at search results. Below is screenshot of what it looks like on native obsidian core theme (and most custom themes have it). Did you remove it? Can you bring it back? Thanks!

![EEFC7717-8B82-4189-A685-4C6ED9055484](https://user-images.githubusercontent.com/64155612/140658859-f584037d-16fe-41e8-8a7a-42dedac715c9.jpeg)

**Comment by colineckert** [comment]
Oh, excellent catch. Originally, the sidebars extended full width, so I hid it as it seemed redundant. But I can put it back so that functionality returns. Should have an updated version ready by tomorrow and will post a comment here so you know when to update your theme. Thanks!

**Comment by GitMurf** [comment]
Awesome! Thanks so much for responding so quickly :) the nice thing about the full screen button is it also covers the side ribbon for even more screen real estate

**Comment by colineckert** [comment]
Ok, just release v1.2.5 which has the full-screen button returned! Let me know if you have any other issues, thanks :)

**Comment by GitMurf** [comment]
Wow thanks for updating so quickly :) much appreciated!
