### ISSUE TITLE
[BUG] The H4 title is displayed incorrectly.

### ISSUE THREAD

**Issue by OnismV** [colineckert/obsidian-things#80]
Hi,
  I really like this theme.
  I use DeepL to translate, please excuse my bad English.
  I am using obsidian on win10 and the bug only appears when I use this theme.
  When I use the Things theme, H4 titles like "#### AAAAaaaa" are displayed as "AAAAAAAA". Lower case letters are displayed in upper case.
  Hope you can fix this bug.
  Thanks.
  

edit mode
![edit mode](https://user-images.githubusercontent.com/97080926/184538298-6c5e4eef-aa14-405b-b713-1557ba1fb1ce.png)

read mode
![read mode](https://user-images.githubusercontent.com/97080926/184538306-b1f39553-6bd5-44f9-80ac-b6736ad6057e.png)

**Comment by colineckert** [comment]
Hey, thanks for creating this issue! H4s have been set as uppercase, but I actually just merged this PR https://github.com/colineckert/obsidian-things/pull/78 to resolve this issue by creating a setting in the Style Settings plugin to make H4s normal case. 

Closing this issue for now, but let me know if you have any issues with the style settings plugin. Thanks again!

**Comment by OnismV** [comment]
Thank you!
