### ISSUE TITLE
Cannot change editor font family

### ISSUE THREAD

**Issue by memeplex** [colineckert/obsidian-things#82]
Obsidian 0.15.9

<img width="733" alt="image" src="https://user-images.githubusercontent.com/2845433/185152686-f7d6a381-27ed-4b24-8b6d-ccdbdb9c474d.png">

Things:

<img width="526" alt="image" src="https://user-images.githubusercontent.com/2845433/185152743-1c0bb4a7-c2fd-4363-ab57-98e09102bc5b.png">

Default:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/2845433/185152826-516443e2-0392-439d-af7e-1dc102620ac0.png">

**Comment by memeplex** [comment]
I realize it can be done using the Style Settings plugin, which is great.

But, anyway, from reading https://github.com/colineckert/obsidian-things/issues/55 I believe I would want to support this from the native settings UI as well.

**Comment by colineckert** [comment]
Thanks, @memeplex for creating this issue! I've fixed this bug and you should not be able to update your font families via the native settings. Just update your theme!

**Comment by memeplex** [comment]
Thanks!!!
