### ISSUE TITLE
Highlight active line

### ISSUE THREAD

**Issue by Chris-mik** [colineckert/obsidian-things#87]
Thank you for this wonderful Obsidian theme!
Is there a way to enable active line highlighting from the style settings of the theme?

**Comment by colineckert** [comment]
Hey @Chris-mik great idea! I've added support for this feature via the Style Settings plugin. Update your theme to v2.1.2 and you can enable it under Style Settings > Things Theme > Features. Let me know if it works and if looks good, please close this issue. Thanks!

**Comment by 7k50** [comment]
Thanks for this very nice theme.

Is there a way to change the CSS color of the _narrow line_ (on the left) in the "active line" marker?
I found a way to change the background color of the active line. But I would like to change the narrow line, which appears to use something related to the Obsidian accent color.
