### ISSUE TITLE
Todoist checkboxes do not align in 0.16.3

### ISSUE THREAD

**Issue by stevedrohan** [colineckert/obsidian-things#89]
Thank-you for this beautiful theme. I love it.

Since moving to .16.x the checkboxes in the todoist plugin no longer align with the item.  In other themes they align well, but not my favorite theme.  

Thank you for your help with this issue. 

![Screenshot 2022-09-23 at 12 21 36 PM](https://user-images.githubusercontent.com/3385928/192007168-df098109-cd7b-4b27-a01a-d7a779bef547.png)

**Comment by colineckert** [comment]
hey @stevedrohan are you still experiencing this issue? i tested locally and the alignment seems to be good now, so closing this issue. if it's not working on your end, pls feel free to reopen. thanks!
