### ISSUE TITLE
Translucency in note pane

### ISSUE THREAD

**Issue by KutuzovGambit** [colineckert/obsidian-things#9]
First off, great theme!!

One issue I notice is that when translucency is enabled in the appearance settings of Obsidian, with your theme the note pane has translucency enabled. Most apps only enable translucency in sidebars but not the main content pane in order to retain readability. Is this something you would consider changing, at least as an optional setting? Thanks!

**Comment by colineckert** [comment]
Hi sorry for the delay in my response! I'm working on a fix for this and hope to share it soon, thank you!

**Comment by colineckert** [comment]
Hi @KutuzovGambit I just released a new version with better support for translucent window in style settings plugin. Update and let me know if you like it and I'll close this issue. Thanks for your patience and I hope you like how it turned out!

**Comment by KutuzovGambit** [comment]
Wonderful! Thanks again for the great theme!
