### ISSUE TITLE
Theme marked as legacy - Obsidian 1.0

### ISSUE THREAD

**Issue by Selenuix** [colineckert/obsidian-things#92]
Obsidian 1.0 just got released and the Things theme is now marked as legacy. 

![image](https://user-images.githubusercontent.com/29508475/195617471-4597d6ee-734e-40a7-aedd-8120b5d6aed8.png)

From the changelog:

> The Theme Gallery has gotten a major overhaul. Themes now support versioning just like plugins. Note: Themes that are not compatible with 0.16 have been marked as "legacy" and cannot be installed until they get updated.

Any plans to make the theme compatible / use versioning?

**Comment by parkin** [comment]
Things is already updated to be compatible with Obsidian 1.0.

You can update to the latest version of Things in Obsidian using Settings > Appearance > Themes click Manage > Things > Check for Updates

![image](https://user-images.githubusercontent.com/1381048/195663101-4dab9990-c91d-4d7f-8cca-23ceef9de3b2.png)

**Comment by amzon-ex** [comment]
I think the update broke a lot of css stylings. Fonts in different parts of the UI are inconsistent and/or oversized.

**Comment by Selenuix** [comment]
Perfect, thank you :)

**Comment by colineckert** [comment]
Things v2 was released yesterday to be compatible with the awesome UI changes introduced in Obsidian 1.0 and the theme is no longer listed as Legacy. Hope you all enjoy the update and lmk your thoughts. Cheers!
