### ISSUE TITLE
The space above the "Tab" bar is too low and too wide. Obsidian - 1.0

### ISSUE THREAD

**Issue by mmdzt** [colineckert/obsidian-things#93]
For example, if I stake the tab bar, that position takes too much space.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/90957271/195637813-1651ebd9-ff0f-4eda-a34f-32b1031f683a.png">

And this is the default theme
It's much thinner and easy to ignore
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/90957271/195638349-93850bed-2eae-4358-bf16-0c69a04581bc.png">

Any plans to modify the theme?

**Comment by mmdzt** [comment]
It has been updated! Thank you very much!

**Comment by colineckert** [comment]
Your welcome! Thanks for using Things!
