### ISSUE TITLE
Hard to see which tab is active

### ISSUE THREAD

**Issue by Niels-NTG** [colineckert/obsidian-things#97]
In the current version of the theme I find it pretty difficult to see at a glance which tab is the active one. There's a difference in the text colour, but it's too subtle to make it stand out sufficiently. See screenshot below for an example:

<img width="702" alt="Schermafbeelding 2022-10-18 om 11 40 43" src="https://user-images.githubusercontent.com/6061595/196396081-9ca31cd0-b6cd-4151-9010-e144bd773ea3.png">

I tested it with all window frame styles. This does not make a notable difference.

When the Obsidian window does not have focus the active tab is much more apparent (see screenshot below). I would suggest something like this should be the style used to indicate the active tab for when the window is in focus as well.
<img width="475" alt="Schermafbeelding 2022-10-18 om 11 46 26" src="https://user-images.githubusercontent.com/6061595/196396872-ad712624-8b33-45a9-9878-3060b434a205.png">

**Comment by Niels-NTG** [comment]
I tried to engineer the solution myself, but couldn't find my way around the web of CSS variables.

**Comment by colineckert** [comment]
Hey, @Niels-NTG I just pushed an update that hopefully makes distinguishing the active tab easier. Try updating your theme and lmk if that helps. thanks!

**Comment by Niels-NTG** [comment]
This is much better. Thanks @colineckert !
